var allAlerts ={
  "mlkday": {
    "alerttype": "branchclosing",
    "startdate": "2022-01-14T15:00:00",
    "enddate": "2022-01-18T07:00:00",
    "alertcopy": "In observance of Martin Luther King Jr. Day, our branches will be closed on Monday, January 17, 2022. To see branch hours or make an appointment please visit our <a href='' target='_blank'>branch locator page</a>.",
    "showpagealert": "TRUE",
    "showloginealert": "FALSE",
    "showonpersonalhp": "TRUE",
    "showonbusinesshp": "TRUE",
    "showoncommercialhp": "TRUE",
    "shadow": "FALSE",
    "directurls": []
  },
  "newyearsdayThisYear": {
    "alerttype": "branchclosing",
    "startdate": "2021-12-31T15:00:00",
    "enddate": "2022-01-03T07:00:00",
    "alertcopy": "In observance of New Year's Day, our branches will be closed on Saturday, January 1, 2022. To see branch hours or make an appointment please visit our <a href='' target='_blank'>branch locator page</a>.",
    "showpagealert": "TRUE",
    "showloginealert": "FALSE",
    "showonpersonalhp": "TRUE",
    "showonbusinesshp": "TRUE",
    "showoncommercialhp": "TRUE",
    "shadow": "FALSE",
    "directurls": []
  },
  "newyearsdayNextYear": {
    "alerttype": "branchclosing",
    "startdate": "2022-12-31T15:00:00",
    "enddate": "2023-01-03T07:00:00",
    "alertcopy": "In observance of New Year's Day, our branches will be closed on Saturday, January 1, 2023. To see branch hours or make an appointment please visit our <a href='' target='_blank'>branch locator page</a>.",
    "showpagealert": "TRUE",
    "showloginealert": "FALSE",
    "showonpersonalhp": "TRUE",
    "showonbusinesshp": "TRUE",
    "showoncommercialhp": "TRUE",
    "shadow": "FALSE",
    "directurls": []
  },
  "presidentsday": {
    "alerttype": "branchclosing",
    "startdate": "2022-02-18T15:00:00",
    "enddate": "2022-02-22T07:00:00",
    "alertcopy": "In observance of Presidents' Day, our branches will be closed on Monday, February 21, 2022. To see branch hours or make an appointment please visit our <a href='' target='_blank'>branch locator page</a>.",
    "showpagealert": "TRUE",
    "showloginealert": "FALSE",
    "showonpersonalhp": "TRUE",
    "showonbusinesshp": "TRUE",
    "showoncommercialhp": "TRUE",
    "shadow": "FALSE",
    "directurls": []
  },
  "memorialday": {
    "alerttype": "branchclosing",
    "startdate": "2022-05-27T15:00:00",
    "enddate": "2022-05-31T07:00:00",
    "alertcopy": "In observance of Memorial Day, our branches will be closed on Monday, May 30, 2022. To see branch hours or make an appointment please visit our <a href='' target='_blank'>branch locator page</a>.",
    "showpagealert": "TRUE",
    "showloginealert": "FALSE",
    "showonpersonalhp": "TRUE",
    "showonbusinesshp": "TRUE",
    "showoncommercialhp": "TRUE",
    "shadow": "FALSE",
    "directurls": []
  },
  "juneteenth": {
    "alerttype": "branchclosing",
    "startdate": "2022-06-17T15:00:00",
    "enddate": "2022-06-21T07:00:00",
    "alertcopy": "In observance of the Juneteenth holiday, our branches will be closed on Monday, June 20, 2022. <br />To see branch hours or make an appointment please visit our <a href='' target='_blank'>branch locator page</a>.",
    "showpagealert": "TRUE",
    "showloginealert": "FALSE",
    "showonpersonalhp": "TRUE",
    "showonbusinesshp": "TRUE",
    "showoncommercialhp": "TRUE",
    "shadow": "FALSE",
    "directurls": []
  },
  "independenceday": {
    "alerttype": "branchclosing",
    "startdate": "2022-07-01T15:00:00",
    "enddate": "2022-07-05T07:00:00",
    "alertcopy": "In observance of Independence Day, our branches will be closed on Monday, July 4, 2022. To see branch hours or make an appointment please visit our <a href='' target='_blank'>branch locator page</a>.",
    "showpagealert": "TRUE",
    "showloginealert": "FALSE",
    "showonpersonalhp": "TRUE",
    "showonbusinesshp": "TRUE",
    "showoncommercialhp": "TRUE",
    "shadow": "FALSE",
    "directurls": []
  },
  "laborday": {
    "alerttype": "branchclosing",
    "startdate": "2022-09-02T15:00:00",
    "enddate": "2022-09-06T07:00:00",
    "alertcopy": "In observance of Labor Day, our branches will be closed on Monday, September 5, 2022. To see branch hours or make an appointment please visit our <a href='' target='_blank'>branch locator page</a>.",
    "showpagealert": "TRUE",
    "showloginealert": "FALSE",
    "showonpersonalhp": "TRUE",
    "showonbusinesshp": "TRUE",
    "showoncommercialhp": "TRUE",
    "shadow": "FALSE",
    "directurls": []
  },
  "columbusday": {
    "alerttype": "branchclosing",
    "startdate": "2022-10-07T15:00:00",
    "enddate": "2022-10-11T07:00:00",
    "alertcopy": "In observance of Columbus Day, our branches will be closed on Monday, October 10, 2022. To see branch hours or make an appointment please visit our <a href='' target='_blank'>branch locator page</a>.",
    "showpagealert": "TRUE",
    "showloginealert": "FALSE",
    "showonpersonalhp": "TRUE",
    "showonbusinesshp": "TRUE",
    "showoncommercialhp": "TRUE",
    "shadow": "FALSE",
    "directurls": []
  },
  "veteransday": {
    "alerttype": "branchclosing",
    "startdate": "2022-11-09T15:00:00",
    "enddate": "2022-11-12T07:00:00",
    "alertcopy": "In observance of Veterans Day, our branches will be closed on Friday, November 11, 2022. To see branch hours or make an appointment please visit our <a href='' target='_blank'>branch locator page</a>.",
    "showpagealert": "TRUE",
    "showloginealert": "FALSE",
    "showonpersonalhp": "TRUE",
    "showonbusinesshp": "TRUE",
    "showoncommercialhp": "TRUE",
    "shadow": "FALSE",
    "directurls": []
  },
  "thanksgivingday": {
    "alerttype": "branchclosing",
    "startdate": "2022-11-23T15:00:00",
    "enddate": "2022-11-25T07:00:00",
    "alertcopy": "In observance of Thanksgiving Day, our branches will be closed on Thursday, November 24, 2022. To see branch hours or make an appointment please visit our <a href='' target='_blank'>branch locator page</a>.",
    "showpagealert": "TRUE",
    "showloginealert": "FALSE",
    "showonpersonalhp": "TRUE",
    "showonbusinesshp": "TRUE",
    "showoncommercialhp": "TRUE",
    "shadow": "FALSE",
    "directurls": []
  },
  "christmasdayThisYear": {
    "alerttype": "branchclosing",
    "startdate": "2021-12-22T15:00:00",
    "enddate": "2021-12-27T07:00:00",
    "alertcopy": "In observance of Christmas Day, our branches will be closed on Saturday, December 25, 2021. To see branch hours or make an appointment please visit our <a href='' target='_blank'>branch locator page</a>.",
    "showpagealert": "TRUE",
    "showloginealert": "FALSE",
    "showonpersonalhp": "TRUE",
    "showonbusinesshp": "TRUE",
    "showoncommercialhp": "TRUE",
    "shadow": "FALSE",
    "directurls": []
  },
  "christmasdayNextYear": {
    "alerttype": "branchclosing",
    "startdate": "2022-12-23T15:00:00",
    "enddate": "2022-12-27T07:00:00",
    "alertcopy": "In observance of Christmas Day, our branches will be closed on Monday, December 26, 2022. To see branch hours or make an appointment please visit our <a href='' target='_blank'>branch locator page</a>.",
    "showpagealert": "TRUE",
    "showloginealert": "FALSE",
    "showonpersonalhp": "TRUE",
    "showonbusinesshp": "TRUE",
    "showoncommercialhp": "TRUE",
    "shadow": "FALSE",
    "directurls": []
  },
  "fraudgeneral": {
    "alerttype": "fraud",
    "startdate": "",
    "enddate": "",
    "alertcopy": "Beware of Scams. There has been a recent increase in customers receiving links to bogus websites and requests to remotely access their devices which have resulted in customers becoming the victim of fraud. Know the signs fraud and what to do if you're in doubt. Learn More >",
    "showpagealert": "TRUE",
    "showloginealert": "FALSE",
    "showonpersonalhp": "TRUE",
    "showonbusinesshp": "",
    "showoncommercialhp": "",
    "shadow": "FALSE",
    "directurls": []
  },
  "fraudalternative": {
    "alerttype": "fraud",
    "startdate": "",
    "enddate": "",
    "alertcopy": "Protect your Personal and Financial Information During times of heightened fear and confusion, such as COVID-19, scammers are looking to gain access to your sensitive account information. We will never ask for personal account information, such as PIN, passcode, account or routing number via text or email. You will never have to click through a link to accept your funds from an email or text message. Please do not respond to any malicious and unsolicited requests that appear to be from M&T Bank.",
    "showpagealert": "TRUE",
    "showloginealert": "FALSE",
    "showonpersonalhp": "TRUE",
    "showonbusinesshp": "",
    "showoncommercialhp": "",
    "shadow": "FALSE",
    "directurls": []
  },
  "impactall": {
    "alerttype": "impact",
    "startdate": "",
    "enddate": "",
    "alertcopy": "We are experiencing multiple system issues that impact branches, Customer Service call center, and online banking. Please try back later. We apologize for the inconvenience. Stay informed>",
    "showpagealert": "TRUE",
    "showloginealert": "FALSE",
    "showonpersonalhp": "TRUE",
    "showonbusinesshp": "",
    "showoncommercialhp": "",
    "shadow": "FALSE",
    "directurls": []
  },
  "callcenterhighvol": {
    "alerttype": "impact",
    "startdate": "",
    "enddate": "",
    "alertcopy": "The Customer Service call center is temporarily unavailable due to higher than normal call volume. Please consider calling back later or using online or mobile banking.",
    "showpagealert": "TRUE",
    "showloginealert": "FALSE",
    "showonpersonalhp": "TRUE",
    "showonbusinesshp": "",
    "showoncommercialhp": "",
    "shadow": "FALSE",
    "directurls": []
  },
  "callcenteronlyclosing": {
    "alerttype": "impact",
    "startdate": "",
    "enddate": "",
    "alertcopy": "The Customer Service call center is temporarily unavailable. Please consider calling back later. Stay Informed >",
    "showpagealert": "TRUE",
    "showloginealert": "FALSE",
    "showonpersonalhp": "TRUE",
    "showonbusinesshp": "",
    "showoncommercialhp": "",
    "shadow": "FALSE",
    "directurls": []
  },
  "branchonlyclosing": {
    "alerttype": "impact",
    "startdate": "",
    "enddate": "",
    "alertcopy": "Branches in your area may be closed due to <WEATHER/ISSUE>. Visit our <a href='' target='_blank'>Branch/ATM directory</a> for specific branch hours and information, and online and mobile banking are always open. Stay informed>",
    "showpagealert": "TRUE",
    "showloginealert": "FALSE",
    "showonpersonalhp": "TRUE",
    "showonbusinesshp": "",
    "showoncommercialhp": "",
    "shadow": "FALSE",
    "directurls": []
  },
  "olboutage": {
    "alerttype": "impact",
    "startdate": "",
    "enddate": "",
    "alertcopy": "M&T Online Banking is temporarily unavailable. If you have any questions regarding your personal M&T accounts or you would like to complete a transaction, please call <a href='tel:1-800-724-2440' target='_blank'>1-800-724-2440</a>. We apologize for the inconvenience.",
    "showpagealert": "TRUE",
    "showloginealert": "FALSE",
    "showonpersonalhp": "TRUE",
    "showonbusinesshp": "",
    "showoncommercialhp": "",
    "shadow": "FALSE",
    "directurls": []
  },
  "ao": {
    "alerttype": "service",
    "startdate": "",
    "enddate": "",
    "alertcopy": "Online account opening is temporarily unavailable and we’re working to resolve the issue. We apologize for the inconvenience. For assistance, please <a href='https://www04.timetrade.com/app/mtcorp/workflows/mtcorp-LPA/schedule?&appointmentTypeGroupId=personalbranch&appointmentTypeId=personalnewacctbranch&resourceId=any&ch=OCT' target='_blank'>Make an Appointment</a>.",
    "showpagealert": "TRUE",
    "showloginealert": "FALSE",
    "showonpersonalhp": "TRUE",
    "showonbusinesshp": "",
    "showoncommercialhp": "",
    "shadow": "FALSE",
    "directurls": [],
    "forceRedStatus": "",
    "status": "green"
  },
  "billpay": {
    "alerttype": "service",
    "startdate": "",
    "enddate": "",
    "alertcopy": "Bill Pay is temporarily unavailable and we’re working to resolve the issue. We apologize for the inconvenience.",
    "showpagealert": "TRUE",
    "showloginealert": "FALSE",
    "showonpersonalhp": "TRUE",
    "showonbusinesshp": "",
    "showoncommercialhp": "",
    "shadow": "FALSE",
    "directurls": [],
    "forceRedStatus": "",
    "status": "green"
  },
  "alerts": {
    "alerttype": "service",
    "startdate": "",
    "enddate": "",
    "alertcopy": "M&T Alerts are temporarily unavailable and we’re working to resolve the issue. We apologize for the inconvenience.",
    "showpagealert": "TRUE",
    "showloginealert": "FALSE",
    "showonpersonalhp": "TRUE",
    "showonbusinesshp": "",
    "showoncommercialhp": "",
    "shadow": "FALSE",
    "directurls": [],
    "forceRedStatus": "",
    "status": "green"
  },
  "mobilebanking": {
    "alerttype": "service",
    "startdate": "",
    "enddate": "",
    "alertcopy": "M&T Mobile Banking is temporarily unavailable and we’re working to resolve the issue. We apologize for the inconvenience.",
    "showpagealert": "TRUE",
    "showloginealert": "FALSE",
    "showonpersonalhp": "TRUE",
    "showonbusinesshp": "",
    "showoncommercialhp": "",
    "shadow": "FALSE",
    "directurls": [],
    "forceRedStatus": "",
    "status": "green"
  },
  "moneysmart": {
    "alerttype": "service",
    "startdate": "",
    "enddate": "",
    "alertcopy": "M&T Money Smart is temporarily unavailable and we’re working to resolve the issue. We apologize for the inconvenience.",
    "showpagealert": "TRUE",
    "showloginealert": "FALSE",
    "showonpersonalhp": "TRUE",
    "showonbusinesshp": "",
    "showoncommercialhp": "",
    "shadow": "FALSE",
    "directurls": [],
    "forceRedStatus": "",
    "status": "green"
  },
  "olb": {
    "alerttype": "service",
    "startdate": "",
    "enddate": "",
    "alertcopy": "M&T Mobile and Online Banking is temporarily unavailable and we’re working to resolve the issue. We apologize for the inconvenience.",
    "showpagealert": "TRUE",
    "showloginealert": "TRUE",
    "showonpersonalhp": "TRUE",
    "showonbusinesshp": "TRUE",
    "showoncommercialhp": "",
    "shadow": "FALSE",
    "directurls": [],
    "forceRedStatus": "",
    "status": "green"
  },
  "mcd": {
    "alerttype": "service",
    "startdate": "",
    "enddate": "",
    "alertcopy": "Mobile Check Deposit is temporarily unavailable and we’re working to resolve the issue. We apologize for the inconvenience.",
    "showpagealert": "TRUE",
    "showloginealert": "FALSE",
    "showonpersonalhp": "TRUE",
    "showonbusinesshp": "",
    "showoncommercialhp": "",
    "shadow": "FALSE",
    "directurls": [],
    "forceRedStatus": "",
    "status": "green"
  },
  "transfers": {
    "alerttype": "service",
    "startdate": "",
    "enddate": "",
    "alertcopy": "Transfers and Internal Payments through M&T Online & Mobile Banking are temporarily unavailable and we’re working to resolve the issue. We apologize for the inconvenience.",
    "showpagealert": "TRUE",
    "showloginealert": "FALSE",
    "showonpersonalhp": "TRUE",
    "showonbusinesshp": "",
    "showoncommercialhp": "",
    "shadow": "FALSE",
    "directurls": [],
    "forceRedStatus": "",
    "status": "green"
  },
  "zelle": {
    "alerttype": "service",
    "startdate": "",
    "enddate": "",
    "alertcopy": "Zelle is temporarily unavailable and we’re working to resolve the issue. We apologize for the inconvenience.",
    "showpagealert": "TRUE",
    "showloginealert": "FALSE",
    "showonpersonalhp": "TRUE",
    "showonbusinesshp": "",
    "showoncommercialhp": "",
    "shadow": "FALSE",
    "directurls": [],
    "forceRedStatus": "",
    "status": "green"
  },
  "zelle3p": {
    "alerttype": "service",
    "startdate": "2022-02-18T07:00:00",
    "enddate": "2022-02-22T07:00:00",
    "alertcopy": "Please be aware that some banks are temporarily unable to receive Zelle payments. You may receive an error if trying to use Zelle to send money to some users.",
    "showpagealert": "FALSE",
    "showloginealert": "TRUE",
    "showonpersonalhp": "TRUE",
    "showonbusinesshp": "TRUE",
    "showoncommercialhp": "",
    "shadow": "FALSE",
    "directurls": [],
    "forceRedStatus": "",
    "status": "green"
  },
  "ivr-feb-2022": {
    "alerttype": "service",
    "startdate": "2022-02-19T07:00:00",
    "enddate": "2022-02-19T18:00:00",
    "alertcopy": "Thank you for your patience today while we experience higher than normal wait times in our Telephone Call Center. For account information, please use M&amp;T Online and Mobile Banking.",
    "showpagealert": "FALSE",
    "showloginealert": "FALSE",
    "showonpersonalhp": "FALSE",
    "showonbusinesshp": "FALSE",
    "showoncommercialhp": "FALSE",
    "shadow": "FALSE",
    "directurls": [],
    "forceRedStatus": "",
    "status": "green"
  },
  "nowalert": {
    "alerttype": "service",
    "startdate": "2022-03-19T12:00:00",
    "enddate": "2022-03-19T15:00:00",
    "alertcopy": "On March 19, 2022 access to account statements and notices will be unavailable due to scheduled system maintenance from approximately 12:00pm - 3:00pm ET. We apologize for the inconvenience",
    "showpagealert": "FALSE",
    "showloginealert": "TRUE",
    "showonpersonalhp": "TRUE",
    "showonbusinesshp": "",
    "showoncommercialhp": "",
    "shadow": "FALSE",
    "directurls": [],
    "forceRedStatus": "",
    "status": "red"
  },
  "zelleReq": {
    "alerttype": "service",
    "startdate": "2022-01-16T00:30:00",
    "enddate": "2022-01-16T05:30:00",
    "alertcopy": "On January 16, 2022 Zelle will be unavailable due to scheduled system maintenance from approximately 12:30am – 5:30am ET. We apologize for the inconvenience.",
    "showpagealert": "FALSE",
    "showloginealert": "TRUE",
    "showonpersonalhp": "TRUE",
    "showonbusinesshp": "",
    "showoncommercialhp": "",
    "shadow": "FALSE",
    "directurls": [],
    "forceRedStatus": "",
    "status": "green"
  },
  "newalert": {
    "alerttype": "service",
    "startdate": "",
    "enddate": "",
    "alertcopy": "PLACE ALERT COPY HERE",
    "showpagealert": "FALSE",
    "showloginealert": "FALSE",
    "showonpersonalhp": "FALSE",
    "showonbusinesshp": "",
    "showoncommercialhp": "",
    "shadow": "FALSE",
    "directurls": [],
    "forceRedStatus": "",
    "status": "green"
  },
  "maint1": {
    "alerttype": "service",
    "startdate": "2022-04-27T21:00",
    "enddate": "2022-05-01T06:00",
    "alertcopy": "Due to scheduled system maintenance, Online and Mobile Banking will be unavailable on Saturday, April 30, 2022 from approximately 9:00pm ET through Sunday, May 1, 2022 at 6:00am ET. Any payments or transfers scheduled before the outage window will still be processed as expected. We apologize for any inconvenience.",
    "showpagealert": false,
    "showloginealert": true,
    "showonpersonalhp": true,
    "showonbusinesshp": false,
    "showoncommercialhp": false,
    "shadow": false,
    "directurls": "",
    "forceRedStatus": "olb,mobilebanking",
    "status": "green"
  },
  "mobplannedout521": {
    "alerttype": "service",
    "startdate": "2022-05-19T12:00",
    "enddate": "2022-05-22T01:01",
    "alertcopy": "Due to scheduled system maintenance, M&T Mobile Banking will be unavailable Saturday, May 21, 2022 from approximately 9:00pm ET through Sunday, May 22, 2022 at 12:00am ET. Access to M&T Online Banking will remain available during this maintenance period. We apologize for the inconvenience.",
    "showpagealert": false,
    "showloginealert": true,
    "showonpersonalhp": false,
    "showonbusinesshp": false,
    "showoncommercialhp": false,
    "shadow": false,
    "directurls": "",
    "status": ""
  },
  "sched071322": {
    "alerttype": "service",
    "startdate": "2022-07-15T17:00",
    "enddate": "2022-07-17T02:00",
    "alertcopy": "<p><b>M&T Mobile & Online Banking Outage</b></p> <p>Due to scheduled system maintenance, some features of M&T Mobile & Online Banking will be unavailable on Saturday, July 16, 2022, from 6:00 pm ET, until Sunday, July 17, 2022, 2:00 am ET.</p> <p>During this time, you will be able to login and view your accounts, but you will not be able to open new accounts, conduct transfers, or update or enroll in services like alerts.</p> <p>Transactions or enrollments made before the maintenance window will still be processed as expected.</p> <p>We apologize for the inconvenience.</p>",
    "showpagealert": false,
    "showloginealert": true,
    "showonpersonalhp": false,
    "showonbusinesshp": false,
    "showoncommercialhp": false,
    "shadow": false,
    "directurls": "",
    "status": "red"
  },
  "sched0716202212pm": {
    "alerttype": "service",
    "startdate": "2022-07-15T17:00",
    "enddate": "2022-07-16T21:59",
    "alertcopy": "On July 16, 2022 the ability to open an account online will be unavailable due to scheduled system maintenance from approximately 6pm – 9pm ET. We apologize for the inconvenience.",
    "showpagealert": true,
    "showloginealert": false,
    "showonpersonalhp": false,
    "showonbusinesshp": false,
    "showoncommercialhp": false,
    "shadow": false,
    "directurls": ["checking-accounts-mandt-bank", "compare-business-checking-options", "m-and-t-simple-checking-for-business", "m-and-t-tailored-business-checking"],
    "status": "red"
  }
}